### ISSUE TITLE
App is not approved by Slack.

### ISSUE THREAD

**Issue by mentatxx** [JackuB/mermaid-preview#1]
Can not add the app to Slack, since it is not approved by Slack

**Comment by JackuB** [comment]
Hey @mentatxx, the app is in Slack's review process. it will take some time, but the aim is to get it approved. 🤞

**Comment by JackuB** [comment]
Mermaid Preview just got approved for App Directory: https://slack.com/apps/A05P92WP51V-mermaid-preview 🎉 

You should be able to install it in your workspaces.
