### ISSUE TITLE
mermaid-preview says flowchart diagram is invalid

### ISSUE THREAD

**Issue by HolisticDeveloper** [JackuB/mermaid-preview#2]
I've just tried mermaid-preview for the first time. It doesn't seem to support the flowchart diagram. I've used the following sample diagram from [Mermaid.live](https://mermaid.live/):

```
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

I get a message back that says "Mermaid diagram is invalid."

**Comment by JackuB** [comment]
Thanks for the report! I'll add it to the test suite. Indeed it's failing for the same issue as here: https://github.com/mermaid-js/mermaid/issues/5204

I'll check if there is a way to get it working.

**Comment by HolisticDeveloper** [comment]
Works for me! Personally I haven't use font-awesome icons a lot, although it does seem like they would be handy.

**Comment by JackuB** [comment]
Good news, with the https://github.com/mermaid-js/mermaid-cli/releases/tag/10.9.0 the icon font is correctly rendered.

![Screenshot 2024-06-16 at 22 54 42](https://github.com/JackuB/mermaid-preview/assets/1788727/4bc67e42-7fc2-4c83-a3be-33c306d5a1bf)
