### ISSUE TITLE
Mermaid js failing with operation timeout

### ISSUE THREAD

**Issue by muffinmike** [JackuB/mermaid-preview#28]
<img width="471" alt="Screenshot 2024-07-09 at 12 34 46 PM" src="https://github.com/JackuB/mermaid-preview/assets/131831722/c01aed93-2148-436e-bef3-9516ccbebd88">

Doesn't happen consistently so I assume its a timeout issue. iirc slack expects a response within 3s which may be aggressive for creating + returning the png. Let me know if there are any other details I can add to help debug.

**Comment by dazinator** [comment]
hitting this today also

**Comment by JackuB** [comment]
Yes, I also ran into this last week myself. I will be migrating off fly.io host.
Their machine startup times are just too variable. I have nothing else to do code-wise as I ack() Slack’s action immediatelly after receiving it. But that’s not enough if Fly.io takes 5+ seconds to provision a machine. ✌️

**Comment by muffinmike** [comment]
@JackuB Makes sense to me, thanks for the response. I'll go ahead and close this since there's nothing code-specific that needs to be changed here.
