### ISSUE TITLE
How do you use it in a private channel?

### ISSUE THREAD

**Issue by lucas-santos-resolver** [JackuB/mermaid-preview#4]
I tried using `/mermaid` in a private channel, but it shows `Mermaid Preview can't automatically join private channels. If it's a private channel, please invite Mermaid bot to it.`. I tried adding the Mermaid bot to the channel; however, it doesn't show up on the participants list.

How do I use it in a private channel?

**Comment by mauleyzaola** [comment]
@lucas-santos-resolver I have that same problem. How did you end up fixing it?
